### ISSUE TITLE
Publish maven artifact

### ISSUE THREAD

**Issue by andreas-mausch** [msink/kotlin-libui#13]
So new projects can just use kotlin-libui as a normal dependency

See #7

**Comment by msink** [comment]
Sure, but I think this should wait for Kotlin 1.3.10 or maybe even 1.3.20.

Now it is a bit rough on edges.

**Comment by msink** [comment]
Well, in Kotlin 1.3.10 some bugs we're fixed, https://youtrack.jetbrains.com/issue/KT-27803

So now publishing to bintray should work, with some tricks - Gradle must be 4.7 (it is), 
'gradle-bintray-plugin' should be '1.8.2-SNAPSHOT' from maven { url 'https://dl.bintray.com/jetbrains/kotlin-native-dependencies' }

But I have very little free time this week for experiments, so if interested - go on :)

**Comment by msink** [comment]
Asked JetBrains decelopers: JetBrains/kotlin-native#2372

**Comment by andreas-mausch** [comment]
Good news with the publishing!

Just to share some thoughts for the numbering scheme: Imo you should *not* align it to the libui version, because you might want to do changes, while the libui version remains the same, and vice versa.

It should probably be alpha, as long as libui is.

So maybe something like 0.1.0 (at least this is what the semver FAQ suggests to start with).

My laptop works again (I broke it during the vacation), so I'm eager to check your changes.

**Comment by andreas-mausch** [comment]
For the windows issue: Maybe the dependsOn is the problem:
`tasks.compileKotlinNative.dependsOn compileWindowsResources`

We can find out which task downloads `msys2-mingw-w64-x86_64-gcc-7.3.0-clang-llvm-lld-6.0.1` and call compileWindowsResources after. So replace compileKotlinNative by something else.

**Comment by msink** [comment]
I tried - seems that there isn't such gradle task.
But maybe JetBrains developers know better.

**Comment by msink** [comment]
Done.

**Comment by msink** [comment]
And to `jcenter()` too.
