### ISSUE TITLE
"ld.lld: error: unable to find library" on CentOS7

### ISSUE THREAD

**Issue by komkomh** [msink/kotlin-libui#23]
Hello.
I tried to work hello-ktx sample according to README in this project. But it doesn't work and output this error.

> Task :samples:controlgallery:linkReleaseExecutableLinux FAILED
/home/komkomh/.konan/dependencies/clang-llvm-6.0.1-linux-x86-64/bin/ld.lld: error: unable to find library -lgtk-3
/home/komkomh/.konan/dependencies/clang-llvm-6.0.1-linux-x86-64/bin/ld.lld: error: unable to find library -lgdk-3
/home/komkomh/.konan/dependencies/clang-llvm-6.0.1-linux-x86-64/bin/ld.lld: error: unable to find library -latk-1.0
/home/komkomh/.konan/dependencies/clang-llvm-6.0.1-linux-x86-64/bin/ld.lld: error: unable to find library -lgio-2.0
/home/komkomh/.konan/dependencies/clang-llvm-6.0.1-linux-x86-64/bin/ld.lld: error: unable to find library -lpangocairo-1.0
/home/komkomh/.konan/dependencies/clang-llvm-6.0.1-linux-x86-64/bin/ld.lld: error: unable to find library -lgdk_pixbuf-2.0
/home/komkomh/.konan/dependencies/clang-llvm-6.0.1-linux-x86-64/bin/ld.lld: error: unable to find library -lcairo-gobject
/home/komkomh/.konan/dependencies/clang-llvm-6.0.1-linux-x86-64/bin/ld.lld: error: unable to find library -lpango-1.0
/home/komkomh/.konan/dependencies/clang-llvm-6.0.1-linux-x86-64/bin/ld.lld: error: unable to find library -lcairo
/home/komkomh/.konan/dependencies/clang-llvm-6.0.1-linux-x86-64/bin/ld.lld: error: unable to find library -lgobject-2.0
/home/komkomh/.konan/dependencies/clang-llvm-6.0.1-linux-x86-64/bin/ld.lld: error: unable to find library -lglib-2.0
e: /home/komkomh/.konan/dependencies/clang-llvm-6.0.1-linux-x86-64/bin/ld.lld invocation reported errors
FAILURE: Build failed with an exception.

My os version is
CentOS Linux release 7.6.1810 (Core) 

Please give me a hint. Thanks

**Comment by msink** [comment]
Maybe not documented here, but documented in upstream libui: https://github.com/andlabs/libui/blob/master/README.md#runtime-requirements
Linux version requires GTK+ 3.10 or newer

**Comment by komkomh** [comment]
Hello

Thank you your quick response. I checked my gtk3 version.
> pkg-config --modversion gtk+-3.0

3.22.30

> pkg-config --libs gtk+-3.0

-lgtk-3 -lgdk-3 -latk-1.0 -lgio-2.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lpango-1.0 -lcairo -lgobject-2.0 -lglib-2.0

**Comment by msink** [comment]
Ok, it's installed properly.
Well, now - where is it installed on CentOS?
If - I can guess - in `/usr/lib64` - please try add it to library path, and rebuild:

```patch
--- a/libui/src/nativeInterop/cinterop/libui.def
+++ b/libui/src/nativeInterop/cinterop/libui.def
@@ -7,7 +7,7 @@ libraryPaths = build libui/build
 
 linkerOpts.osx = -lobjc -framework Foundation -framework AppKit
 
-linkerOpts.linux = -L/usr/lib/x86_64-linux-gnu -L/usr/lib \
+linkerOpts.linux = -L/usr/lib/x86_64-linux-gnu -L/usr/lib64 -L/usr/lib \
     -lgtk-3 -lgdk-3 -latk-1.0 -lgio-2.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 \
     -lcairo-gobject -lpango-1.0 -lcairo -lgobject-2.0 -lglib-2.0 -lm -ldl
 
```

**Comment by komkomh** [comment]
Thank you!
I was able to solve the problem.
I'm sorry for the basic questions.

**Comment by msink** [comment]
So `-L/usr/lib64` helped on CentOS?
If yes - I'll add it to next published version.

**Comment by komkomh** [comment]
Yes, I found gtk3 in
-L/usr/lib64
