### ISSUE TITLE
Depends on old version of libcrypt

### ISSUE THREAD

**Issue by squidink7** [msink/kotlin-libui#47]
When executing an application created with this library on linux, it looks for libcrypt.so.1 which on Arch Linux has been deprecated and replaced with libcrypt.so.2. This issue can be solved simply by creating a symlink, which means theres no compatibility issues requiring the older version of the library, so I would recommend updating the dependency to the newer version.

**Comment by msink** [comment]
How this can be fixed here?
Kotlin/Native compiler and linker use sysroot with very old Linux version, not host computer libraries.
And only JetBrains Kotlin team can update that sysroot, AFAIK.

**Comment by squidink7** [comment]
Ahh, I'm no expert with these kinds of things as I'm new to kotlin. I just noticed that the error only occurred when using this library which caused me to assume that's where the issue was caused.
