### ISSUE TITLE
Switch to kotlin-multiplatform plugin

### ISSUE THREAD

**Issue by andreas-mausch** [msink/kotlin-libui#7]
Hi, this is awesome!

Is there an easy way to add kotlin-libui as a dependency when I create a new project, or does kotlin-libui *have* to be in the parent gradle project?

**Comment by msink** [comment]
When this project will be converted from deprecated 'konan' plugin to 'kotlin-multiplatform' -- it can be published to maven, and used as regular dependency. But now I do not have much free time for this, sorry.

**Comment by andreas-mausch** [comment]
Hey, I've seen you pushed some commits regarding the multiplatform plugin. We were working on it in parallel.

We gonna merge what we have now, but maybe please give a hint next time you are working on it so we don't do the same work twice.

We have some additional clean-up like a single build.gradle for all samples, hope you like it. :)

**Comment by msink** [comment]
Well - please check my work,

**Comment by msink** [comment]
Well, then please check my work - I'm sure it needs cleanup, it was mostly copy-paste from various sources.

About samples - not sure, I intentionally tried to keep them isolated so one can use it as template for new repository.

**Comment by msink** [comment]
Also - I didn't want to go too far from official samples - all this stuff is very experimental, there are dragons.
Sometimes if it works in gradle does not mean it works in IDEA or CLion.
In my approach - with single preset - code completion works in CLion, with multiple presets - I cannot make it work.

**Comment by msink** [comment]
I picked and merged obvious cleanup parts, rest should wait a while, at least for next Kotlin version.

**Comment by andreas-mausch** [comment]
See #14. @msink feel free to close the issue.
